# Borrowed from https://gist.github.com/stellasphere/9490c195ed2b53c707087c8c2db4ec0c
wmo_codes <- function(){
  tibble(
  code = c(0, 1, 2, 3, 45, 48, 51, 53, 55, 56, 57, 61, 63, 65, 66, 67,
           71, 73, 75, 77, 80, 81, 82, 85, 86, 95, 96, 99),
  day_description = c(
    "Sunny", "Mainly Sunny", "Partly Cloudy", "Cloudy", "Foggy", "Rime Fog",
    "Light Drizzle", "Drizzle", "Heavy Drizzle", "Light Freezing Drizzle",
    "Freezing Drizzle", "Light Rain", "Rain", "Heavy Rain",
    "Light Freezing Rain", "Freezing Rain", "Light Snow", "Snow", "Heavy Snow",
    "Snow Grains", "Light Showers", "Showers", "Heavy Showers",
    "Light Snow Showers", "Snow Showers", "Thunderstorm",
    "Light Thunderstorms With Hail", "Thunderstorm With Hail"
  ),
  day_image = c(
    "www/icons/01d@2x.png",
    "www/icons/01d@2x.png",
    "www/icons/02d@2x.png",
    "www/icons/03d@2x.png",
    "www/icons/50d@2x.png",
    "www/icons/50d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/10d@2x.png",
    "www/icons/10d@2x.png",
    "www/icons/10d@2x.png",
    "www/icons/10d@2x.png",
    "www/icons/10d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/09d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/13d@2x.png",
    "www/icons/11d@2x.png",
    "www/icons/11d@2x.png",
    "www/icons/11d@2x.png"
  ),
  night_description = c(
    "Clear", "Mainly Clear", "Partly Cloudy", "Cloudy", "Foggy", "Rime Fog",
    "Light Drizzle", "Drizzle", "Heavy Drizzle", "Light Freezing Drizzle",
    "Freezing Drizzle", "Light Rain", "Rain", "Heavy Rain",
    "Light Freezing Rain", "Freezing Rain", "Light Snow", "Snow", "Heavy Snow",
    "Snow Grains", "Light Showers", "Showers", "Heavy Showers",
    "Light Snow Showers", "Snow Showers", "Thunderstorm",
    "Light Thunderstorms With Hail", "Thunderstorm With Hail"
  ),
  night_image = c(
    "www/icons/01n@2x.png",
    "www/icons/01n@2x.png",
    "www/icons/02n@2x.png",
    "www/icons/03n@2x.png",
    "www/icons/50n@2x.png",
    "www/icons/50n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/10n@2x.png",
    "www/icons/10n@2x.png",
    "www/icons/10n@2x.png",
    "www/icons/10n@2x.png",
    "www/icons/10n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/09n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/13n@2x.png",
    "www/icons/11n@2x.png",
    "www/icons/11n@2x.png",
    "www/icons/11n@2x.png"
  )
)
}
